#!/bin/bash
# usage: conv-to-gguf <model-path> <outfile>
#
set -e
source ./scripts/common

convert() {
    python3 ${LLAMA_HOME}/convert.py $1 --outfile $2 --outtype $3 $4
}

if [ $# -eq 0 ]; then
  echo "usage: conv-to-guf <path>" >&2
  exit 1
fi

if [ ! -d ${LLAMA_BUILD_DIR} ]; then
    echo "llama.cpp not found"
    echo "Please run check-deps first"
    exit 1
fi

convert $1 $2 f16 $3
